apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bjpb14c3o-go 
  janus-idp.io/tekton: bjpb14c3o-go
  backstage.io/kubernetes-id: bjpb14c3o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bjpb14c3o-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  